language: node_js
node_js:
- stable
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: TAMInX/FJPHtWIxYtQm0pLnBRYQCz0dSwl6TyTZtiHc33wMdvXpUREIIRttj2nqqQbKmBcQFL9Q7VErSWPvbRaRCKKlifsrPL+BYo0bHigxpVWUJV5HdzvlyjGUrvhmluc+v7VESVNWKCsA0PZb/7ecTuJ/lmJAnZJbGrDgUnqIn7BtdD7HpMQJeKG0SuPzzJNBPi2gNY/7eI0WWQu76E5Qk7XhJtlphxf3OO+qdwFgDcMwv0N2eIyPlOOYQPj7SzZNJX6M3Yj7fs2mway+52yctUT7+m4hURfCs75SpYS+RtXenhLsKQd1aZxXmmQB12+baIxn9n4h/72kyMS8HsZlNGiEOcY8BO7guc8uYb/BNvjMiZxyua0Qo8VBzo4z6dH4VvVilxOJ/qiW6nXLLhVUHWAkcqXJY3iHto+4fihTVJNP41z6KOfbLTBHWU7d5XzbkykzRs9XqSoz7M4DywLz5oiSRBJl1xmXZ5UtD0r+M6uJTR8dBVL6fse2h9VoYSs/PKoTuI1RoNDQd1DrHe1K5KwAx3hD0VMQpj2H4qXBIhMsviuZXDcDsZUtPV9OmkcwzFq0QxtP2EBASsYo5scWDI4uFLvi0OQEoAAzgi5VS4cvO1437rBuM5RI1p4qAbOGObc/IL8a1iaruTZqDvXDiiobtqKu9mssCPfoMBt8=
